### PR TITLE
fix audit logs and introduce actual http errors instead of only handling 400's

### LINKED ISSUE #231: Fetching auditlog entires results in Exception
I tried fetching auditlogs using
```Java            catnip.rest().guild().getGuildAuditLog("507517900127469568").user("416902379598774273").fetch()
```
And that exception got thrown
```Feb 08, 2019 7:05:23 PM io.vertx.core.impl.ContextImpl
SCHWERWIEGEND: Unhandled exception
java.lang.ClassCastException: io.vertx.core.json.JsonArray cannot be cast to java.util.List
	at com.mewna.catnip.rest.requester.AbstractRequester.lambda$handleResponse$2(AbstractRequester.java:256)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mewna.catnip.rest.requester.AbstractRequester.handleResponse(AbstractRequester.java:254)
	at com.mewna.catnip.rest.requester.AbstractRequester$1.lambda$onResponse$1(AbstractRequester.java:206)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by SamOphis**
__***yes this is tested***__
but nah fr, this is tested and should close #231 (except for the fact that i can't reproduce the 400 bad request)

it wasn't my code causing the issues either which is a first. now any response code which is not 429 or 400 creates a neatly-formatted `ResponseException` which you can respond to by using `CompletionStage#exceptionally`.

i'd recommend creating a new tag for this as `0.13.3` is effectively broken when dealing with audit logs

### CODE REVIEW

**Comment by SamOphis** [comment]
An example of the stack trace of a `ResponseException`:
```
java.util.concurrent.CompletionException: com.mewna.catnip.rest.ResponseException: HTTP Error Code: 403 | JSON Message: Missing Permissions | JSON Error Code: 50013
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:632)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.mewna.catnip.rest.requester.AbstractRequester.handleResponse(AbstractRequester.java:274)
	at com.mewna.catnip.rest.requester.AbstractRequester$1.lambda$onResponse$1(AbstractRequester.java:209)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.mewna.catnip.rest.ResponseException: HTTP Error Code: 403 | JSON Message: Missing Permissions | JSON Error Code: 50013
	at com.mewna.catnip.rest.requester.AbstractRequester.handleResponse(AbstractRequester.java:272)
	... 9 more
```

File: src/main/java/com/mewna/catnip/rest/ResponseException.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+ * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+ */
+
+package com.mewna.catnip.rest;
+
+/**
+ * @author SamOphis
+ * @since 02/09/2019
+ */
+public class ResponseException extends Exception {
```
Comment (natanbc) [inline src/main/java/com/mewna/catnip/rest/ResponseException.java]: maybe subclass RuntimeException instead?

File: src/main/java/com/mewna/catnip/rest/requester/AbstractRequester.java [hunk 2]
```diff
@@ -263,6 +264,16 @@ protected void handleResponse(final int statusCode, final long requestEnd, final
...
                 request.bucket().requestDone();
+            } else if(statusCode > 400) {
+                final JsonObject response = payload.object();
+                final String message = response.getString("message", "No message.");
+                final int code = response.getInteger("code", -1);
+                final ResponseException exception = code != -1
+                        ? new ResponseException(String.format("HTTP Error Code: %d | JSON Message: %s | JSON Error Code: %d", statusCode, message, code))
+                        : new ResponseException(String.format("HTTP Error Code: %d | JSON Message: %s", statusCode, message));
+                request.future().completeExceptionally(exception);
+                updateBucket(r.route(), headers, -1, latency);
```
Comment (natanbc) [inline src/main/java/com/mewna/catnip/rest/requester/AbstractRequester.java]: bucket should be updated before completing the future
